
KEYWORD_FUNCTION = "function"
KEYWORD_VAR = "var"
KEYWORD_CONST = "const"
KEYWORD_CONST = "const"
KEYWORD_RETURN = "return"
KEYWORD_TRUE = "true"
KEYWORD_FALSE = "false"
KEYWORD_IF = "if"
KEYWORD_WHILE = "while"
KEYWORD_FOR = "for"
KEYWORD_DEL = "delete"
KEYWORD_IMPORT = "import"
KEYWORD_WRITEBUF = "write"
KEYWORD_READBUF = "read"
KEYWORD_SIZEOF = "sizeof"
KEYWORD_UNSAFE = "unsafe"
KEYWORD_FLUSH = "flush"
KEYWORD_NULL = "null"
KEYWORD_NATIVE = "native"
KEYWORD_REFERENCE = "ref"
KEYWORD_IMAGINARY_UNIT = "im"
KEYWORD_COMPLEX_CALL = "complex"
KEYWORD_CLASS = "class"


TOKEN_TYPE_VAR = "NH:VAR"
TOKEN_TYPE_CONST = "NH:CONST"
TOKEN_TYPE_FUNCTION = "NH:FUNCTION"
TOKEN_TYPE_RETURN = "NH:RETURN"
TOKEN_TYPE_IDENT = "NH:IDENT"
TOKEN_TYPE_FLOAT = "NH:FLOAT"
TOKEN_TYPE_INT = "NH:INT"
TOKEN_TYPE_STRING = "NH:STRING"
TOKEN_TYPE_LPAREN = "NH:LPAREN"
TOKEN_TYPE_RPAREN = "NH:RPAREN"
TOKEN_TYPE_LBRACE = "NH:LBRACE"
TOKEN_TYPE_RBRACE = "NH:RBRACE"
TOKEN_TYPE_LSBRACE = "NH:LSBRACE"
TOKEN_TYPE_RSBRACE = "NH:RSBRACE"
TOKEN_TYPE_COMMA = "NH:COMMA"
TOKEN_TYPE_SEMICOLON = "NH:SEMICOLON"
TOKEN_TYPE_EQUAL = "NH:EQUAL"
TOKEN_TYPE_PLUS = "NH:PLUS"
TOKEN_TYPE_MINUS = "NH:MINUS"
TOKEN_TYPE_STAR = "NH:STAR"
TOKEN_TYPE_DOUBLE_STAR = "NH:DOUBLE STAR"
TOKEN_TYPE_SLASH = "NH:SLASH"
TOKEN_TYPE_DOUBLE_SLASH = "NH:DOUBLE SLASH"
TOKEN_TYPE_MOD = "NH:MOD"
TOKEN_TYPE_AND = "NH:AND"
TOKEN_TYPE_OR = "NH:OR"
TOKEN_TYPE_XOR = "NH:XOR"
TOKEN_TYPE_LOGICAL_AND = "NH:LOGAND"
TOKEN_TYPE_LOGICAL_OR = "NH:LOGOR"
TOKEN_TYPE_EQUALITY = "NH:EQUALITY"
TOKEN_TYPE_INEQUALITY = "NH:INEQUALITY"
TOKEN_TYPE_TRUE = "NH:TRUE"
TOKEN_TYPE_FALSE = "NH:FALSE"
TOKEN_TYPE_IF = "NH:IF"
TOKEN_TYPE_RIGHTSHIFT = "NH:RSHIFT"
TOKEN_TYPE_LEFTSHIFT = "NH:LSHIFT"
TOKEN_TYPE_DEL = "NH:DEL"
TOKEN_TYPE_NOT = "NH:NOT"
TOKEN_TYPE_REV = "NH:REV"
TOKEN_TYPE_IMPORT = "NH:IMPORT"
TOKEN_TYPE_WHILE = "NH:WHILE"
TOKEN_TYPE_FOR = "NH:FOR"
TOKEN_TYPE_GREATER = "NH:GREATER"
TOKEN_TYPE_SMALLER = "NH:SMALLER"
TOKEN_TYPE_GREATER_EQ = "NH:GREATEREQ"
TOKEN_TYPE_SMALLER_EQ = "NH:SMALLEREQ"
TOKEN_TYPE_WRITEBUF = "NH:WRITEBUF"
TOKEN_TYPE_READBUF = "NH:READBUF"
TOKEN_TYPE_SIZEOF = "NH:SIZEOF"
TOKEN_TYPE_UNSAFE = "NH:UNSAFE"
TOKEN_TYPE_FLUSH = "NH:FLUSH"
TOKEN_TYPE_NULL = "NH:NULL"
TOKEN_TYPE_NATIVE = "NH:NATIVE"
TOKEN_TYPE_LAMBDA = "NH:LAMBDA"
TOKEN_TYPE_REFERENCE = "NH:REF"
TOKEN_TYPE_INC = "NH:INC"
TOKEN_TYPE_DEC = "NH:DEC"
TOKEN_TYPE_IMAGINARY_UNIT = "NH:IMAGINARY"
TOKEN_TYPE_COMPLEX_CALL = "NH:COMPLEX"
TOKEN_TYPE_CLASS = "NH:CLASS"


KEYWORDS = {
    KEYWORD_VAR: TOKEN_TYPE_VAR,
    KEYWORD_FUNCTION: TOKEN_TYPE_FUNCTION,
    KEYWORD_RETURN: TOKEN_TYPE_RETURN,
    KEYWORD_TRUE: TOKEN_TYPE_TRUE,
    KEYWORD_FALSE: TOKEN_TYPE_FALSE,
    KEYWORD_IF: TOKEN_TYPE_IF,
    KEYWORD_DEL: TOKEN_TYPE_DEL,
    KEYWORD_IMPORT: TOKEN_TYPE_IMPORT,
    KEYWORD_WHILE: TOKEN_TYPE_WHILE,
    KEYWORD_FOR: TOKEN_TYPE_FOR,
    KEYWORD_WRITEBUF: TOKEN_TYPE_WRITEBUF,
    KEYWORD_READBUF: TOKEN_TYPE_READBUF,
    KEYWORD_SIZEOF: TOKEN_TYPE_SIZEOF,
    KEYWORD_UNSAFE: TOKEN_TYPE_UNSAFE,
    KEYWORD_FLUSH: TOKEN_TYPE_FLUSH,
    KEYWORD_NULL: TOKEN_TYPE_NULL,
    KEYWORD_CONST: TOKEN_TYPE_CONST,
    KEYWORD_NATIVE: TOKEN_TYPE_NATIVE,
    KEYWORD_REFERENCE: TOKEN_TYPE_REFERENCE,
    KEYWORD_IMAGINARY_UNIT: TOKEN_TYPE_IMAGINARY_UNIT,
    KEYWORD_COMPLEX_CALL: TOKEN_TYPE_COMPLEX_CALL,
    KEYWORD_CLASS: TOKEN_TYPE_CLASS
}


SINGLE_CHAR_TOKENS = {
    "(": TOKEN_TYPE_LPAREN,
    ")": TOKEN_TYPE_RPAREN,
    "{": TOKEN_TYPE_LBRACE,
    "}": TOKEN_TYPE_RBRACE,
    "[": TOKEN_TYPE_LSBRACE,
    "]": TOKEN_TYPE_RSBRACE,
    ",": TOKEN_TYPE_COMMA,
    ";": TOKEN_TYPE_SEMICOLON,
    "=": TOKEN_TYPE_EQUAL,
    "+": TOKEN_TYPE_PLUS,
    "-": TOKEN_TYPE_MINUS,
    "*": TOKEN_TYPE_STAR,
    "/": TOKEN_TYPE_SLASH,
    "&": TOKEN_TYPE_AND,
    "|": TOKEN_TYPE_OR,
    "^": TOKEN_TYPE_XOR,
    "!": TOKEN_TYPE_NOT,
    "~": TOKEN_TYPE_REV,
    ">": TOKEN_TYPE_GREATER,
    "<": TOKEN_TYPE_SMALLER,
    "%": TOKEN_TYPE_MOD
}


DOUBLE_CHAR_OPERATORS = {"=": TOKEN_TYPE_EQUALITY, "&": TOKEN_TYPE_LOGICAL_AND, "|": TOKEN_TYPE_LOGICAL_OR, ">": TOKEN_TYPE_RIGHTSHIFT, "<": TOKEN_TYPE_LEFTSHIFT, "++": TOKEN_TYPE_INC, "--": TOKEN_TYPE_DEC, "/": TOKEN_TYPE_DOUBLE_SLASH, "*": TOKEN_TYPE_DOUBLE_STAR}
MULTIPLE_CHAR_OPERATORS = {"->": TOKEN_TYPE_LAMBDA, ">=": TOKEN_TYPE_GREATER_EQ, "<=": TOKEN_TYPE_SMALLER_EQ, "!=": TOKEN_TYPE_INEQUALITY}


COMMENT = "//"
MAIN_FUNCTION = "main"
STANDARD_NATIVE_MODULE_NAME = "natives"